MANIFEST.in
setup.py
social_core/tests/backends/open_id_connect.py

This file is needed by OpenIdConnectTestMixin. Any packages/projects wanting to use the mixin need the test key.

Including testkey.pem

---

social_core/backends/qq.py

I have to decode response content first, as the type of response.content is 'bytes' but the JSON object requires 'str'.

response content of QQ should be decoded first

---

social_core/backends/azuread.py

Calling the `auth_extra_arguments()` method of the parent class allows to add extra params to the request. Handy to include `login_hint` and `domain_hint` among others.
Azure AD oauth call docs: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-code#request-an-authorization-code

Allow extra arguments for azuread backend.

---

social_core/backends/mediawiki.py

If an error occurs during the initial handshake, the error
message is currently not visible to developers.
This commit checks if the response starts with an error
message and raises an exception.

Mediawiki: Raise exception if response is error

---

social_core/backends/google.py

So users who do see that error know that `id_token` is supported.
Closes #59

Note `id_token` in GooglePlusAuth's AuthMissingParameter

---

social_core/backends/saml.py

Add SAML attributes passed from IDP to extra_data on UserSocialAuth
model. Should behave as other backends do.

add extra_data method to process SAMLAuth

---

social_core/strategy.py

Once the code has been used, it should not validate the address again.
Maybe I'm missing something in the code, but it seems that the verified attribute is not really used and because of this the validation codes are valid even after they have been used and it's possible to reuse the partial URLs.

Avoid reusing verification codes

---

social_core/backends/base.py

The strategy and redirect_uri passed as kwargs are now preferred to those values set in the constructor. The primary goal of this change is to ensure that the strategy has a request attached so that downstream code can make use of the request.
Fixes #73

Updated BaseAuth.authenticate() to prefer kwargs

---

CHANGELOG.md
social_core/utils.py

This causes middlewere to catch the exception,
which prevents the server error, for example when
user presses back button on browser and repeaats the request
with already used grant code.

Raise AuthForbidden on 401.

---

CHANGELOG.md
social_core/backends/fitbit.py

Before the results was like:
`{'Authorization': 'Basic b"o9834yf0398efyq30br87fyb30f8u3hyb"'}`
There was the `b""` Python formating for byte strings. So I added a decode step.
Final result is like:
`{'Authorization': 'Basic o9834yf0398efyq30br87fyb30f8u3hyb'}`

Fix auth header formatting problem. (fitbit)

---

CHANGELOG.md
social_core/backends/udata.py
social_core/tests/backends/test_udata.py

Add a generic base class for [udata](http://udata.readthedocs.io/en/latest/) backend, set as a base class given that French are not the only ones using that platform.
I need some help to understand how tests are working. I don't get how to set up the username for instance, do I have to create a dummy account on the platform?
(Incoming social-docs PR counter-part)

Add udata/datagouvfr backend

---

CHANGELOG.md
social_core/backends/base.py
social_core/tests/backends/test_dummy.py

The idea is from [@haikuginger](https://github.com/python-social-auth/social-core/pull/84#issuecomment-303146208) and answers [Issue #85](https://github.com/python-social-auth/social-core/issues/85).
We allow the user to get all extra data without having to specify each key explicitly in an `EXTRA_DATA` setting; this has many use cases and is backwards compatible by virtue of defaulting to `False`.
P.S. @omab If this looks good, I can add the necessary documentation in the docs repo. Excited to continue contributing to this lib.

Allow to get all extra data in a response through setting.

---

CHANGELOG.md
social_core/backends/patreon.py
social_core/tests/backends/test_patreon.py

As per documentation at https://www.patreon.com/platform/documentation/oauth
We were using this with an older python-social-auth (0.2.21), but I've ported this forward to social-core so upstream benefits and it's not stuck in our forked version.
Tests should pass - am having issues running tox locally, but will see what your CI (assuming Travis) does.

Adds Patreon OAuth2 backend

---

social_core/backends/disqus.py

Disqus now returns the following error if redirect_state is used:
Invalid Request: Invalid parameter: redirect_uri (should match predefined callback URI)

Fix DisqusOAuth2 backend since the callback URL is now validated

---

CHANGELOG.md
social_core/backends/saml.py

NameID is a single-valued value, which means that when [0] is applied to it, we grab
just the first letter instead of the full nameid.
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>
Fixes #101

Update get_attr to use the entire value if an attribute is single-valued

---

social_core/backends/bitbucket.py

Removal of the blocking method with `NotImplementedError` makes the backend work with refreshing tokens. Tested with
```python
def get_token(user):
social = user.social_auth.get(provider='bitbucket-oauth2')
if social.access_token_expired():
strategy=load_strategy()
backend=social.get_backend(strategy)
instance=social.get_backend_instance(strategy)
data = super(backend, instance).refresh_token(social.extra_data['refresh_token'])
data.update({'auth_time': datetime.now().timestamp()})
data['expires']=data.pop('expires_in')
return social.access_token
token=get_token(user)
print(token)
```

Remove unnecessary blocker for refresh_token in BitBucketOAuth2 backend

---

CHANGELOG.md
social_core/backends/oauth.py

Issue #133 fixed:
Use the `constant_time_compare` method from the `social_core.utils` package to prevent [timing attacks](https://cryptocoding.net/index.php/Coding_rules#Compare_secret_strings_in_constant_time) against the state token during the state token validation.

Fix Issue #133: Constant time compare for state validation

---

social_core/backends/gitlab.py

https://docs.gitlab.com/ce/api/v3_to_v4.html:
> API V3 will be removed in GitLab 9.5, to be released on August 22, 2017. In the meantime, we advise you to make any necessary changes to applications that use V3. The V3 API documentation is still available.

gitlab: use api v4

---

social_core/backends/weixin.py

Weixin oauth api doc requires an additional paramter: 'scope': 'snsapi_login'.
Otherwise, it would not work.

fix weixin default scope

---

social_core/backends/phabricator.py
social_core/tests/backends/test_phabricator.py

This adds a OAuth2 backend for Phabricator to allow users to authenticate using Phabricator login.
See: https://phabricator.wikimedia.org/T179202

Add Phabricator backend

---

social_core/backends/openstreetmap.py

OpenStreetMap is [moving to https by default](https://github.com/openstreetmap/operations/issues/190) and all oauth calls made to the http endpoint after that [will fail](https://github.com/openstreetmap/openstreetmap-website/pull/1341#issuecomment-258439266). This simple PR converts all openstreetmap.org http calls to https.
No related issue.
While I was at it, I converted the other openstreetmap.org URLs to use https.

Use https URLs for openstreetmap.org.

---

CHANGELOG.md
social_core/backends/linkedin.py

Fixes #173
As per [the LinkedIn docs](https://developer.linkedin.com/docs/oauth2), the OAuth token should be passed back to LinkedIn as a request header. It should be as `Authorization: Bearer ...`, though, instead of `oauth_token`. The latter makes LinkedIn crash with an internal server error.

Fix header being set to pass the token in the LinkedIn OAuth2 back-end

---

social_core/backends/azuread_b2c.py
social_core/tests/backends/test_azuread_b2c.py

Please take a look. This is a straight copy from our fork of the legacy repo (https://github.com/appsembler/python-social-auth/pull/5).
I still need to do the following:
It would nice to do the following as well:
Closes #100 and Closes #157

Backend for Azure Active Directory B2C

---

CHANGELOG.md
social_core/backends/linkedin.py
social_core/tests/backends/test_linkedin.py

LinkedIn uses 2 separate access tokens for their mobile sdk client and the web client.
Currently python-social-auth uses the web client. This means that in a project which has user account registrations possible from both a web view and a mobile client, when the user registers in the mobile client, he will not be able to make authentication requests to the web server, since the mobile access key doesn't work for web requests.
This merge request solves the issue by adding a separate authentication backend which imitates LinkedIn mobile SDK requests.
https://stackoverflow.com/a/39032743/2529583
https://stackoverflow.com/a/41221636/2529583
Please tell me if there are any improvements required.

Added LinkedIn mobile authentication backend

---

social_core/backends/base.py

When updating extra_data in `UserMixin.refresh_token`, some fields with data get overridden with `None`, because they are stored with the alias and not the original name (like `expires_in` → `expires` and `id` → `user_id` for google plus).
So this should fix those cases.

Add aliased extra_data field on refresh_token

---

social_core/backends/saml.py

In that case, the method as originally given returns the first character of the UID string instead of the full UID.

Allow for cases where SAML user_permanent_id is not a list

---

social_core/backends/oauth.py

I had a case of 411 (Content-Length required) on Jive because the parameters were sent as data. #185

Use params instead of data in token request, if the method is GET.

---

social_core/backends/azuread_b2c.py

Fix, policy name could start with capitalized letters "B2C_"

azuread_b2c policy name check fix

---

setup.py

Updated setup.py to use extras_require to differentiate between python 2 and python 3 requirements.  This gets along with pipenv. Fixes #142 
Now pipenv users may add some additional specifications to their Pipfile to get the correct versions installed consistently.
```
[packages]
social-auth-core = "*"
python-openid = {version=">=2.2.5", markers="python_version<'3.0'"}
python3-openid = {version=">=3.0.10", markers="python_version>='3.0'"}
defusedxml = {version=">=0.5.0rc1", markers="python_version>='3.0'"}
```

Use extras_require for version differences

---

CHANGELOG.md
social_core/backends/github.py

GitHub understands the `state` parameter on their OAuth flows:
https://developer.github.com/apps/building-oauth-apps/authorization-options-for-oauth-apps/#web-application-flow
The current configuration using `redirect_state` actually breaks OAuth flows using GitHub Apps as they [don't support any extra parameters in the redirect URI](https://developer.github.com/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps/)

Remove additional 'redirect_state' parameter from GitHub backend

---

social_core/backends/microsoft.py

'`mail`' field is often null when the accounts are not native Microsoft one, and in those cases, `userPrincipalName` field is used. You can find some more information on [here](https://stackoverflow.com/questions/47344384/microsoft-azure-ad-graph-api-how-do-i-retrieve-a-users-email-address). With this change it tries to get `email` from `userPrincipalname` if the `mail` field is empty. (The check for the type of `userPrincipalName` can be improved, although if `userPrincipalName` is not email, in that case, you can expect that value of `mail` will be there. )

updated code to fallback on userPrincipalName for email - Microsoft backend

---

social_core/utils.py

Running my test with enabled warnings I have
```bash
../lib/social_core/utils.py:138: DeprecationWarning: invalid escape sequence \w
value = re.sub('[^\w\s-]', '', value).strip().lower()
../lib/social_core/utils.py:139: DeprecationWarning: invalid escape sequence \s
return re.sub('[-\s]+', '-', value)
```
This PR uses raw strings.

Fixed literal warnings in slugify

---

CHANGELOG.md
social_core/backends/keycloak.py
social_core/tests/backends/test_keycloak.py

This patchset adds a Keycloak OAuth 2.0 backend based on the Keycloak OpenID Connect 1.0 API.

Add Keycloak backend with tests

---

social_core/tests/requirements-python2.txt
social_core/tests/requirements-python3.txt

unittest2 now supports Python 3 and the old unittest2py3k package is
abandoned: https://pypi.org/project/unittest2/.

Unpin the test requirements and use unittest2 for Python 3

---

social_core/backends/slack.py

contract correct username when USERNAME_WITH_TEAM settings enabled

fix slack backend get_user_details

---

social_core/backends/oauth.py

This e.g. fixes the flow with linkedin: https://developer.linkedin.com/docs/oauth2#
They either raise `user_cancelled_login` or `user_cancelled_authorize` which are both caught by this change. I would argue, that I did not overgeneralize, but if that's an issue, the error code matching could be narrowed down further.

More generically detect cancelling in oauth2 process_error

---

social_core/backends/mediawiki.py

get_user_details should return more things from MediaWiki instance:
* email
* confirmed_email
* editcount
* rights
* groups
* registered (time when user registered)
* blocked

MediaWiki: get_user_details should return more details

---

social_core/backends/yandex.py
social_core/tests/backends/test_yandex.py

When user log in to yandex service with social network account (e.g. vk.com), they `default_email` (and `emails` accordingly) could be empty. When it occurs, auth process fails with an error:
```
...
File "/home/advent/site/repo/backend/auth/backend.py", line 17, in get_user_details
response.get('emails', [''])[0],
IndexError: list index out of range
```

[bugfix] Yandex backend: Do not fail when no email is present

---

CHANGELOG.md
social_core/backends/google.py
social_core/tests/backends/test_google.py

Fix for #300.
Google+ APIs will be shut down on March 7, 2019. More details here
https://developers.google.com/+/api-shutdown
> This will be a progressive shutdown, with intermittent failures
> starting as early as January 28, 2019.
Replacing the G+ endpoint with
https://www.googleapis.com/oauth2/v3/userinfo works for the
google-oauth2 backend with almost no extra changes.
This new endpoint is currently used by
[Google's OpenID Connect](https://developers.google.com/identity/protocols/OpenIDConnect)
implementation as OpenID Connect `userinfo_endpoint`. It might not be
the best idea to hard code it like that in the long term. But this was
the one endpoint that is actually mentioned in some Google
documentation as far as I could find. Please feel free to propose better
alternatives if you …

Move away from Google+ API usage in google-oauth2 backend

---

social_core/pipeline/user.py

The comment says to update "SOCIAL_AUTH_PROTECTED_FIELDS" but the name of the setting is actually "SOCIAL_AUTH_PROTECTED_USER_FIELDS"

Fixes comment

---

CHANGELOG.md
social_core/backends/azuread_tenant.py

Override the get_user_id function from AzureADOAuth2 as the uid does not exist in the azure ad tenant response and produces a "None" UID within the social authentication.  See issue #70 . The Azureb2c backend has the exact same override function. Have tested locally and the changes work as expected.

Update azuread_tenant.py to fix NoneType error

---

CHANGELOG.md
social_core/backends/google.py
social_core/tests/backends/test_google.py

i.e. the "default" OAuth2 method of presenting the access token to the
resource server. Which is of course supported by both:
- https://www.googleapis.com/plus/v1/people/me (current user data url)
- https://www.googleapis.com/oauth2/v3/userinfo (see #301)
Passing secrets via GET query params is not great. Resource server
access logs usually retain the entire url including the GET query
params. `requests` library when used with DEBUG logging level will also
log the entire request url including the query params on the OAuth
client side.
This also drops the unnecessary `alt=json` query param.
This change should be compatible with #301.

Pass access token via Authorization header to google user data url

---

CHANGELOG.md
social_core/backends/linkedin.py
social_core/tests/backends/test_linkedin.py

Recently, Linkedin announced that all the developers need to migration to Linkedin v2 API and OAuth2 by March 1st, 2019. 
This PR
- Added support for Linkedin OAuth2.0 using v2 API
- Removed unsupported Oauth1 from the Linkedin backend
These changes do not require any modification to the existing application built with python-social-core.
PS: Also updated the LinkedIn documentation on social-docs. [PR Link](https://github.com/python-social-auth/social-docs/pull/55)

Updated LinkedinOAuth2 to use v2 APIs #310

---

social_core/backends/github.py

From the [document](https://developer.github.com/v3/#user-agent-required):
> All API requests MUST include a valid User-Agent header. Requests with no User-Agent header will be rejected. We request that you use your GitHub username, or the name of your application, for the User-Agent header value. This allows us to contact you if there are problems.
I got 403 forbidden when login with github.
> Your access to this site has been restricted.
It turns out that if add User-Agent then everything is fine.

bugfix: github backend need `SEND_USER_AGENT`

---

setup.py

Fixes #342 
Defines the content type of the long description as Markdown so that PyPI will render it correctly.
See https://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=long_description_content_type for details on the definition of `long_description_content_type`. I use it on a personal repository so that I can write my README in markdown but get the benefits of RST in PyPI rendering. 
Here's an example:
- Definition in setup.py: https://github.com/ryanwilsonperkin/circleci-flaky/blob/master/setup.py#L16
- Rendered: https://pypi.org/project/circleci-flaky/
P.S. If this seems like an approach you'd like to take, I can send similar PRs for the other repos in this org.

Add long_description_content_type for PyPi rendering

---

social_core/utils.py

`hmac.compare_digest` is available in both Python 2/3
and provides time constant comparison of ascii and binary
values. It is safe for cryptographic use to prevent timing
attacks.

Use hmac.compare_digest for value comparison

---

CHANGELOG.md
social_core/backends/google_openidconnect.py

GoogleOpenIdConnect was still using the deprecated Google+ API. This PR updates the URL to be the currently supported version and adds a changelog entry.

Replace deprecated Google+ API usage in GoogleOpenIdConnect

---

social_core/backends/auth0.py

It's useful to know if the user's email address has been verified. In my case, I'm using this field in a pipeline to require a verified email before merging to an existing user.

Add email_verified to user details

---

social_core/backends/shopify.py

Shopify v5 introduces the mandatory requirement to provide a version when setup.
https://github.com/Shopify/shopify_python_api#-breaking-change-notice-for-version-500-

Prepare for Shopify SDK v5

---

social_core/backends/naver.py

Exceptions are thrown to prevent DOM errors from getting unsolicited entries when using Naver login

Naver Social Login Missing Gender, Profile.. etc Key find Error Fixed

---

social_core/backends/openstack.py
social_core/backends/openstackdev.py

OpenStack Community is used to OpenID services:
http://openstackid-dev.openstack.org/
http://openstackid.org/
Both are included.

Add OpenStack Backends

---

requirements-python2.txt
requirements-python3.txt
social_core/storage.py

Unicode in username should be covert to ASCII is better than remove

Fix auto remove unicode characters in username

---

CHANGELOG.md
social_core/backends/github.py

https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters
> GitHub is deprecating authentication to the GitHub API using query parameters, such as using a access_token query parameter .......
https://developer.github.com/v3/auth/#basic-authentication

[Github] Pass access token in a header.

---

CHANGELOG.md
social_core/backends/mailru.py
social_core/tests/backends/test_mailru.py

There is already backend for mailru:
https://python-social-auth.readthedocs.io/en/latest/backends/mailru.html
https://github.com/python-social-auth/social-core/blob/master/social_core/backends/mailru.py
which basically use https://my.mail.ru/ - old social network for authentication.
I think it is a good idea to do a new backend for the new mail.ru Oauth - https://oauth.mail.ru/docs

Mailru backend issue 403 - close403

---

social_core/tests/actions/test_associate.py
social_core/tests/backends/open_id_connect.py
social_core/tests/backends/test_broken.py
social_core/tests/backends/test_twitter.py
social_core/tests/backends/test_utils.py
social_core/tests/test_storage.py

```
social_core/tests/backends/test_twitter.py::TwitterOAuth1IncludeEmailTest::test_login
/home/travis/build/asherf/social-core/social_core/tests/backends/test_twitter.py:258: PendingDeprecationWarning: Please use assertEqual instead.
self.assertEquals(user.email, 'foo@bar.bas')
social_core/tests/backends/test_utils.py::GetBackendTest::test_get_missing_backend
/home/travis/build/asherf/social-core/social_core/tests/backends/test_utils.py:44: PendingDeprecationWarning: Please use assertRaisesRegex instead.
'Missing backend "foobar" entry'):
```

Fix assert depercations.

---

CHANGELOG.md
social_core/pipeline/user.py

This tiny PR allows developers to ignore default protected user fields: username, id, pk and email
To fully ignore them, set SOCIAL_AUTH_NO_DEFAULT_PROTECTED_USER_FIELDS to True.
Of course, you can add your own protected fiels by setting them in  `SOCIAL_AUTH_PROTECTED_USER_FIELDS`.
This PR will help me, removing my uggly workaround here: umap-project/umap#754
This PR is related to :
- #348
- #263
- #432

Allow to ignore default protected user fields

---

social_core/backends/atlassian.py

According to the API documentation here https://developer.atlassian.com/cloud/jira/platform/oauth-2-authorization-code-grants-3lo-for-apps/ the Auth URL is auth.atlassian.com, and my own attempts to use this did not work until I changed the URL to that.

Fix Atlassian API url

---

social_core/pipeline/user.py

The field names produced by psa might not map directly to the field names existing on a user model/schema. A mapping could be set in the settings that maps psa fields to program fields if a 1 to 1 mapping exists.
The committed change to `user_details` solves my immediate problem (map "fullname" to a field that exists in my `User` object), but there are other ways of doing it: instead of doing it in the `user_details` pipeline it could probably be done in the `social_details` pipeline, and instead of doing it in code it could be mentioned in the documentation that adapting psa field names to user model field names can be done in x, y, z ways. Regardless, how to do this should be documented/pointed to wherever custom users are mentioned.
Settings name: *_USER_FIELD_MAPPING.
This is one …

Allow renaming of user field names

---

social_core/backends/apple.py

It improves the key validation process trying to get just the requested `kid` (key id) instead of trying all available keys (https://appleid.apple.com/auth/keys).
It's better and safer try to validate using the signing key for this jwt.
Currently, all available Apple public keys are iterated trying to validate the jwt.

Try to validate the correct Apple key

---

social_core/backends/saml.py

If the IDP returns an empty list, return None rather than throwing.

Protect attribute access against empty lists

---

social_core/backends/apple.py

- add ability for users to supply aud for JWT as a list. This enables apple backednd to be used by both iOS login and web from / other sources login, because iOS provides bundle id as client and web from login requires service id to be supplied (to match against defined return urls and allowed domains)
- if there's no first/last name in the response return None so that the User model is not updated to empty strings if user_details is used in the pipeline
your code._
solves …

Some fixes for Apple backend:

---

social_core/strategy.py

The `clean_partial_pipeline` process consists cleans the token from two places:
- The database
- The session
The clean up process is database works seamlessly since the `Partial` object is used to perform the clean up. The clean up from the session however inadvertently removes the `partial_token` for the **new** partial function instead of the old one because it doesn't check that the session token actually matches the `partial_token`.
This PR checks the `partial_token` in the session before popping it.
This fixes #454 
help! This is simply a reminder of what we are going to …

Clean up the right `partial_token` in the session

---

social_core/backends/google.py
social_core/tests/backends/test_google.py

The Google OpenID backend was discontinued on the server side in 2015, in favor of OpenID Connect (our `GoogleOpenIdConnect` backend).
https://support.google.com/accounts/answer/6206245
Fixes #462. Fixes #472.
This is needed to get Travis passing again.
your code._

Remove discontinued GoogleOpenId backend

---

social_core/backends/apple.py
social_core/backends/azuread_b2c.py
social_core/backends/azuread_tenant.py
social_core/backends/google.py
social_core/backends/open_id_connect.py
social_core/tests/backends/test_google.py
social_core/tests/backends/test_keycloak.py

Several backends passed an incorrect and/or unverified `algorithms` argument to jwt.decode. The `apple` backend passed an unused `algorithm` argument instead. The `azuread_b2c`, `azuread_tenant`, and `open_id_connect` backends passed a value from the untrusted JWT header, potentially opening up a vulnerability to symmetric/asymmetric confusion attacks. Additionally, the `azuread_b2c` and `azuread_tenant` backends incorrectly passed it as a string rather than a list.
your code._
- (What lint?)
Any …

Pass correct algorithms argument to jwt.decode

---

requirements-base.txt

PyJWT 2.0.0 has a breaking change for the current release, pin to a version less than 2.0
```
File "/usr/local/lib/python3.6/site-packages/social_core/backends/azuread_tenant.py", line 6, in <module>
from jwt import DecodeError, ExpiredSignature, decode as jwt_decode
ImportError: cannot import name 'ExpiredSignature'
```

Preventing installing v2.0.0 of PyJWT

---

CHANGELOG.md
social_core/backends/paypal.py
social_core/tests/backends/test_paypal.py

Add PayPal and PayPal Sandbox backend support. Fixes https://github.com/python-social-auth/social-core/issues/329.
your code._
I tested integration with [social-app-django](https://github.com/python-social-auth/social-app-django). Even though I didn't find it strictly necessary, it is recommended adding the following to settings.py to exactly match PayPal's authorization URL.
Paypal backend
`SOCIAL_AUTH_PAYPAL_OAUTH2_AUTH_EXTRA_ARGUMENTS = {"flowEntry": "static"}`
PayPal Sandbox backend …

Added PayPal OAuth backend support

---

social_core/backends/okta.py

Closes #524.
This change ensures that the configuration endpoint `/.well-known/openid-configuration` is appended to the configured Okta API_URL rather than replacing the whole slug.
The current approach used to generate the URL Okta applications truncates the provided `API_URL` then appends `/.well-known/openid-configuration` to it. So for custom applications, `mycompany.okta.com/oauth2/<app-identifier>/.well-known/openid-configuration` is instead truncated to `mycompany.okta.com/.well-known/openid-configuration` which won't 404 but may provide incorrect information.
Tests pass, but I couldn't find any lint config.

[Okta] Properly join configuration URLs

---

CHANGELOG.md
social_core/backends/discord.py

Discord has announced that their API, including OAuth2 endpoints, have migrated to discord.com and that at some point support for the old discordapp.com will be discontinued.  This change updates social_core's Discord back end to point to the updated domain name.
This is a configuration change, in anticipation of future breakage should Discord discontinue support for discordapp.com
your code._
I tested the update in a Django app that uses Discord OAuth2 for authentication: d20hex.herokuapp.com

resolves #525 - Discord API endpoints migrating to discord.com

---

social_core/backends/kakao.py

In kakao.py backend, client_secret was not set to fetch user's token.
This patch just add client_secret to `#auth_complete_params` in `kakao.py`.
According to [kakao documentation](https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#request-token) for fetching user's token,
if oauth application was set to use secure `ON`, client_secret must be set!
if not, just passed that value is `None` or not.
your code._
`client_secret` is not required parameter, but must be set if developer turn on …

Fix: kakao backend do not use client_secret even though required

---

social_core/backends/azuread.py
social_core/backends/azuread_b2c.py
social_core/backends/azuread_tenant.py
social_core/tests/backends/test_azuread_b2c.py
social_core/tests/backends/test_keycloak.py

The release of PyJWT 2.0.0 last week included some backwards-incompatible changes.
This adapts some tests and the Azure backends to support the new release (while still supporting the older 1.7.1 version).
One suggestion to solve the problems was to pin PyJWT down to 1.7.1 (that is #532).
The issue was also discussed a little in #503.
(The tests are failing before this PR. It fixes them)
(One test has been freezing for me locally; I thought it may have been an issue with my setup, but I've seen that it froze in CI as well. I skipped it locally, after verifying that it freezes the same way with either PyJWT 1.7.1 or 2.0.0. The skipping is done in 
3809cd1 which is part of the followup PR of tentative changes #537)
This PR is made on …

Support PyJWT 2.0.0

---

social_core/backends/apple.py

Decoded `id_token` doesn't contain name info, so we have to get such info from `self.data`
Solves #482 #501

Get Apple user first & last name from `self.data`

---

social_core/backends/orcid.py
social_core/tests/backends/test_orcid.py

Added a new USER_DATA_ID attribute for the ORCIDOAuth2 and ORCIDMemberOAuth2 classes (and their associated sandbox modes).
Alterations made to self.user_data() call to pass the access_token as a Bearer token to that endpoint. Reference: [https://github.com/ORCID/ORCID-Source/blob/master/orcid-web/ORCID_AUTH_WITH_OPENID_CONNECT.md#other-endpoints] for more details.
Alterations made to the get_user_details() as the orcid parameter is now longer accessible at response['orcid'] instead it is at response['orcid-identifier']['path'].

Amends to social_core.backends.orcid.py

---

CHANGELOG.md
social_core/backends/base.py
social_core/tests/backends/test_dummy.py

With a setting of `SOCIAL_AUTH_WHITELISTED_DOMAINS` set to `gmail.com`, a separate system storing
the domain as `Gmail.com` would be rejected. According to [RFC 1035](https://tools.ietf.org/html/rfc1035) the domain should be checked in a case insensitive manner.
This applies only to the domain portion of whitelisted email addresses as well, e.g. `foo@bar.com` is distinct from `FOO@bar.com`.
I was unable to make the change as cleanly as I would have liked, since it appears that misconfiguring the `SOCIAL_AUTH_WHITELISTED_EMAILS` setting by giving it a domain instead of a valid email is implicitly supported, see https://github.com/python-social-auth/social-core/blob/dddb1784fa54468a09f552ca299f60017f4f6aa9/social_core/tests/backends/test_dummy.py#L111.
Please check the type of change your …

Make WHITELIST_* settings properly case insensitive

---

social_core/backends/zoom.py

At the moment, the expiration is not saved for Zoom Oauth. This adds support if i understand the setup properly. The `expiration_timedelta()` method handles the `expires` value actually referring to the timedelta to expiration in seconds.
https://github.com/python-social-auth/social-core/blob/4e4b635e6095c5bce2b5f4f996b5baa3f23f3ad8/social_core/storage.py#L80-L92
your code._

Support access_token expiration for Zoom backend

---

CHANGELOG.md
social_core/backends/slack.py

Slack user identity API requires access token to be provided in Bearer headers.
https://api.slack.com/methods/users.identity#arg_token
bug as described here: https://github.com/python-social-auth/social-core/issues/570

BUGFIX: Slack backend user_data should provide access_token

---

social_core/backends/arcgis.py

The ArcGIS Rest API for OAuth supports using the refresh_token, so it should be included in EXTRA_DATA by default. See https://developers.arcgis.com/rest/users-groups-and-items/token.htm

Add refresh_token to EXTRA_DATA

---

CHANGELOG.md
social_core/pipeline/user.py
social_core/tests/models.py
social_core/tests/test_pipeline.py

The behavior and documentation for `PROTECTED_USER_FIELDS` used to imply that the fields would be set on user create but then be immutable afterwards. Both the behavior and later the documentation has since changed https://github.com/python-social-auth/social-core/commit/8aab8099a2345ccf7deaa358da3d45e1af9ef8f7 to always protect userfields. However that change has created some confusion (see related Stackoverflow and GIthub issues)
In many cases, you want the initial field for a user but then not to overwite it later on. An example might be a user who logs in as Jonathan from their Gmail but then later updates their nick to Jon for our service.
This change introduces a setting called `IMMUTABLE_USER_FIELDS` which is a peer of `PROTECTED_USER_FIELDS` but allows initial setting of the …

IMMUTABLE_USER_FIELDS: Add a setting for immutable user fields

---

CHANGELOG.md
social_core/backends/gitea.py
social_core/tests/backends/test_gitea.py

This is modeled after gitlab/github.
Gitea oauth docs: https://docs.gitea.io/en-us/oauth2-provider/
User api: https://try.gitea.io/api/swagger#/user/userGetCurrent
Tested with weblate authenticating against gitea, can be tried in the wild at https://weblate.bubu1.eu which allows singing in with codeberg.org accounts.
your code._

add gitea as an oauth2 backend

---

social_core/tests/test_partial.py

Simple fix in the name of the variable used in this TestCase to correct a typo in the word "session".
Changes all usage of `mock_sesstion_set` to `mock_session_set`

Fix typo in PartialDecoratorTestCase mock name

---

social_core/store.py

Instead just import `pickle` module.
Python3+ automatically uses cPickle if it is available.
From the Python 3 release notes:
> A common pattern in Python 2.x is to have one version of a module implemented in pure Python, with an optional accelerated version implemented as a C extension; for example, pickle and cPickle. This places the burden of importing the accelerated version and falling back on the pure Python version on each user of these modules. In Python 3.0, the accelerated versions are considered implementation details of the pure Python versions. Users should always import the standard version, which attempts to import the accelerated version and falls back to the pure Python version.
_Put an `x` in the boxes that apply. You …

Don't try to import cPickle module

---

social_core/backends/okta.py

A Change was made in 3.4.0.0 commit (0a49eb5) which creates an improper "well-known" URL.  Change it back please
your code._

Fix Properly join configuration URLs

---

social_core/backends/globus.py

When `JWT_ALGORITHMS = [RS256]` was hard coded in [backends/open_id_connect.py](https://github.com/python-social-auth/social-core/blob/master/social_core/backends/open_id_connect.py), web apps with the Globus backend started throwing `social_core.exceptions.AuthTokenError: Token error: Invalid signature`. This PR overwrites JWT_ALGORITHMS in the Globus backend.

Set a JWT signature algorithm for the Globus backend to RS512

---

.github/workflows/test.yml
requirements-saml.txt
tox.ini

Add Python 3.10 to the test matrix.
your code._

ci: Add Python 3.10

---

requirements-saml.txt

After investing a lot of time into this issue, I realised it only appears to happen only on Linux and not on Windows. I started to debug the methods and calls and it seemed to be an issue with XML parsing. The latest successful CI run used `lxml` version `4.6.4` and after version `4.7.1` it started to break. I did not inverstigate what could cause this seemingly platform dependent issue but there is also an [open issue](https://github.com/onelogin/python3-saml/issues/292) in `python3-saml`. I chose the easier path and pinned the version of `lxml` under `4.7.0` which seems to solve the issue.
the PR. If you're unsure about any of them, don't hesitate to ask. …

Fix unstable SAML test

---

social_core/exceptions.py
social_core/pipeline/social_auth.py
social_core/tests/actions/test_disconnect.py
social_core/tests/test_exceptions.py

There are two exceptions, `NotAllowedToDisconnect` and `AuthAlreadyAssociated`, which do not define a `__str__` function. After looking through the code I did not find any valid reason why they should not look like the others. I changed them to work like any other exception which makes their handling easier.
your code._

Unify exceptions

---

social_core/backends/open_id_connect.py

This change, proposed [here](https://github.com/mpdavis/python-jose/pull/171#issuecomment-574311477), fixed Signature verification errors we had with ping identity.

Assume RSA256 if key "alg" not set in open_id_connect.py

---

social_core/backends/saml.py

Remove server_port from request_info.
Resolve issue #609 - Stop passing server_port to python3-saml
server_port has been deprecated by python3-saml, see: https://github.com/onelogin/python3-saml/pull/276
If the server application is running behind a load balancer or a reverse proxy the request port might not match the SAML configuration.
- [ x] Other (please describe): Changes in reaction to a deprecation in dependency
your code._
Any other information that is important to this PR such as screenshots …

Removes server_port from request_info

---

social_core/backends/oauth.py
social_core/backends/open_id_connect.py
social_core/backends/vault.py
social_core/tests/backends/test_okta.py
social_core/tests/backends/test_open_id_connect.py
social_core/tests/backends/test_vault.py

This is a more generic solution to PR #668 - for consideration.
In this PR, the OpenIdConnectAuth class is enhanced so that it can be instantiated directly, as a "generic" OIDC connector.
To enable this, it also makes the OAuth2 authentication mechanism configurable (i.e. form post or HTTP Basic), and uses OIDC discovery to select this automatically.
Vault then becomes an empty subclass of OpenIdConnectAuth, since it's an out-of-the-box OIDC provider.
I believe this *shouldn't* break existing code, and all tests pass, but it would be wise to check the other OpenIdConnectAuth subclasses just in case.
the PR. If you're unsure about any of them, don't hesitate …

Add backend for Hashicorp Vault (alternative approach)

---

CHANGELOG.md
social_core/backends/openinfra.py

Add a new backend that's functionally equivalent to the existing OpenStackOpenId backend, but uses the id.openinfra.dev provider.
Resolves feature request (issue #753)
- social_core.tests.backends.test_dummy.ExpirationTimeTest fails for me locally at line 132; it also fails locally without my patch.  I tried to troubleshoot it, but I'm not sure what's going on there.
- it's basically the same as an existing backend except for the URL; and the existing backend doesn't have any tests (looks like most of the subclasses of OpenIdAuth don't have unit tests).  I'll be happy to add tests if you can point me at an example.
None.

Add OpenInfraOpenId backend (#753)

---

docker-compose.yml
social_core/backends/azuread_b2c.py
social_core/tests/backends/test_azuread_b2c.py

This is similar to [PR 459](https://github.com/python-social-auth/social-core/pull/459). I kept the policy name as an extra argument. This appears to be the default endpoint suggested by Azure AD B2C which is probably less confusing. I also made the b2clogin.com endpoint using the `authority_host` property. I have updated the corresponding tests as well as the docker-compose.yml to test with these Python versions: 3.6.12 3.7.16 3.8.16 3.9.16 3.10.10 3.11.2. I have documentation updates drafted and I can propose those changes if this PR is accepted. 
Documentation for the endpoints can be found here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/b2clogin
As proposed the `base_url` would be `https://{tenant_name}.{authority_host}/{tenant_name}.onmicrosoft.com` where …

Update Azure AD B2C base URL to match updated endpoints

---

social_core/backends/azuread_tenant.py

Issue: https://github.com/python-social-auth/social-core/issues/695
Documentation
If your app has custom signing keys as a result of using the claims-mapping ( https://learn.microsoft.com/en-us/azure/active-directory/develop/active-directory-claims-mapping ) feature, you must append an appid query parameter containing the app ID to get a jwks_uri pointing to your app's signing key information, which should be used for validation.
Source: https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#validating-tokens
help! This is simply a reminder of what we are …

add appid query parameter for azuread

---

social_core/backends/nk.py

The issue that was fixed in this PR has been described in the #811 issue. In short, it fixes the `ImportError` that occurs when importing the `nk` backend.

Fix the ImportError occuring on urllib

---

CHANGELOG.md
social_core/backends/keycloak.py

As explained in:
- #813 
Currently, it is not possible to change the `ID_KEY` of the keycloak provider, even though this feature was meant to be present (according to the docstring). The `ID_KEY` is basically the claim used to map a user.
With this change, it is now possible to set the `ID_KEY` to any field present either in details or in the returned token:
```python
SOCIAL_AUTH_KEYCLOAK_ID_KEY = "email" # use the keycloak user email (from details)
SOCIAL_AUTH_KEYCLOAK_ID_KEY = "sub" # use the keycloak user id (from token)
```
help! This is simply a reminder of what we are going …

Make Keycloak's ID_KEY configurable

---

.github/workflows/test.yml
.pre-commit-config.yaml
docker-compose.yml
setup.py
tox.ini

Drop support for Python versions not supported upstream.
your code._

deps: Drop support for old Python versions

---

requirements-base.txt
requirements-openidconnect.txt
setup.py
social_core/backends/auth0.py
social_core/backends/open_id_connect.py
social_core/tests/backends/test_auth0.py
social_core/tests/backends/test_open_id_connect.py

Replace `python-jose` with `pyjwt` (see #503).
your code._
As discussed in #503 some changes was done to perform the migration:
- add `calc_at_hash` static method to `OpenIdConnectAuth` since PyJWT does not support validating claims which are not part of JWT RFCs (see https://github.com/jpadilla/pyjwt/pull/296)
- manual add `"at_hash"` claim in `OpenIdConnectTestMixin.prepare_access_token_body` (see above)
- add `"aud"` claim in `Auth0OAuth2Test.access_token_body` because PyJWT behaves different from …

Replace jose with pyjwt

---

social_core/backends/saml.py

Application has only one IDP, if someway we can set default IDP which can be added as RelayState in case its not provided. IDP has flexibility to pass RelayState IDP information during SSO, but not in case of logout request.
**Reference**: https://github.com/python-social-auth/social-core/issues/632
```
|   File "/openedx/venv/lib/python3.8/site-packages/social_django/utils.py", line 49, in wrapper
|     return func(request, backend, *args, **kwargs)
|   File "/openedx/venv/lib/python3.8/site-packages/social_django/views.py", line 31, in complete
|     return do_complete(request.backend, _do_login, user=request.user,
|   File "/openedx/venv/lib/python3.8/site-packages/social_core/actions.py", line 45, in do_complete
|     user = backend.complete(user=user, *args, **kwargs)
|   File …
```

fix: SAML: IDP initiated logout request comes with RelayState and it causes error

---

social_core/backends/wlcg.py
social_core/tests/backends/test_wlcg.py

Adding the WLCG IAM backend testing site. 
your code._
I have tested using this backend with a local galaxy server. I can get id_token, access_token and refresh_token and things seem to work as expected.

New backend for the WLCG IAM testing site

---

social_core/backends/linkedin.py
social_core/tests/backends/test_linkedin.py

LinkedIn OAuth2 has been deprecated as of August 2023 and been replace with OpenID connect.
This pull request adds LinkedIn OpenID Connect. It has a few specific adjustments as LinkedIn does not send any "nonce" and therefore does not work with the regular OpenID Connect implementation.
Thanks to #829 for the idea and the hint on the OpenID Connect auth base class.
your code._

Add new backend for LinkedIn OpenID Connect

---

social_core/backends/open_id_connect.py

Fix validation error when the `at_hash` claim is absent. 
- Fix #849
- Refs #849
- Refs #819 
your code._

Skip 'at_hash' claim validation when missing

---

CHANGELOG.md
social_core/backends/facebook.py

Version 12.0 of the API is only available until February 8th, 2024 after which requests will be force upgraded to version 13.0.
Version 18.0 is the latest available version and there are no changes to the endpoints requested by social-core so we can jump straight to the latest available version.
Changelog: https://developers.facebook.com/docs/graph-api/changelog.
your code._

Update the Facebook API version from 12.0 to 18.0

---

social_core/backends/apple.py

When creating an application that uses 1 backend and multiple frontends (webapp and iOS), the backend needs to know to what App ID or Service ID you want the access token from Apple.
Now we can just sent the `client_id` together with the `provider` and `code`. That will make it possible support using AppleID for webapp and iOS app on the same backend.
your code._

Make AppleID work with multiple identifiers

---

social_core/backends/openstreetmap_oauth2.py
social_core/tests/backends/test_openstreetmap_oauth2.py

Fixes #758
Adding OAuth 2.0 support for OpenStreetMap, since the existing OAuth 1.0a support will be [sunset in June 2024](https://community.openstreetmap.org/t/oauth-1-0a-and-http-basic-auth-shutdown/108490).
Multiple applications using python-social-auth won't be able to authenticate anymore at that point.
your code._
I've added more details, including a screen recording,  in this comment: https://github.com/python-social-auth/social-core/issues/758#issuecomment-1913232732
Edits:
* I forced-pushed …

[feat] Add OAuth2 support for OpenStreetMap

---

social_core/backends/etsy.py
social_core/backends/oauth.py
social_core/tests/backends/oauth.py

Resolves Issue: https://github.com/python-social-auth/social-core/issues/879
Note: This is a breaking change and could potentially break authentications.

fix: Etsy OAuth2 Authentication bugs

---

social_core/backends/box.py

Set redirect_state parameter to False for Box backend as Box recognise the state parameter.
your code._

Set redirect_state to False for box backend

---

social_core/backends/steam.py
social_core/tests/backends/test_steam.py

The implementation of SteamOpenId does not validate identity URL and could be impersonated by attackers.
your code._

fix: SteamOpenId does not validate identity url

---

requirements-base.txt

Remove release candidate version from accepted range to avoid having later release candidates being installed.
Fixes #911
your code._
- n/a? Lint and unit tests pass locally with my changes
- n/a? I have added tests that prove my fix is effective or that my feature works
- n/a? I have added documentation …

Fix defusedxml requirement

---

CHANGELOG.md
social_core/backends/orcid.py

Handle the case where the user has not registered a `family-name` and ORCID returns `None`.
This addresses [https://github.com/python-social-auth/social-app-django/issues/355](https://github.com/python-social-auth/social-app-django/issues/355) and #602 (which it appears to duplicate). Full credit to [paloha](https://github.com/paloha), who very clearly [explained](https://github.com/python-social-auth/social-app-django/issues/355#issuecomment-1568685404) the issue and proposed the simple fix included here.
As a brief summary: ORCID does not require users to enter a family name and returns a `family-name` key with value `None` in this case. The code expects that key to either be absent, or contain a dictionary. This leads to an `AttributeError` after successful login by a user who has not …

Fix ORCID login when no family name was given

---

social_core/backends/telegram.py

Make username always a string to avoid errors in the user pipeline.
Bugfix https://github.com/python-social-auth/social-core/issues/918
your code._
I was unable to build the make tests docker image
everything ended in error
failed to solve: process "/bin/sh -c /pyenv.sh" did not complete successfully: exit code: 1
I’m not sure what this is connected with (perhaps due to the blocking of the docker hub in Russia or something else, but because of this I could not run the tests)
upd: dont know how, but …

Fix https://github.com/python-social-auth/social-core/issues/918

---

social_core/pipeline/user.py

According to https://python-social-auth.readthedocs.io/en/latest/configuration/settings.html, "All settings can be defined per-backend by adding the backend name to the setting name, like SOCIAL_AUTH_TWITTER_LOGIN_URL". This changes user.py to actually use per-backend settings for options like USERNAME_IS_FULL_EMAIL.
Note that get_username is always called with a backend, but user_details isn't, so a different version of `setting' is needed for the two.
your code._
- [X?] Lint and unit tests pass …

Allow per-backend user pipeline settings

---

social_core/backends/asana.py
social_core/backends/exacttarget.py
social_core/backends/linkedin.py
social_core/backends/open_id_connect.py
social_core/storage.py
social_core/tests/backends/test_dummy.py
social_core/tests/backends/test_livejournal.py
social_core/tests/backends/test_ngpvan.py
social_core/tests/backends/test_open_id_connect.py

Rather than using the `datetime.utcnow()` and `datetime.utcfromtimestamp()` methods which produce timezone-naive datetime objects, we should instead use `datetime.now()` and `datetime.fromtimestamp()` with UTC provided as the timezone, in order to create timezone-aware datetime objects.
This removes the DeprecationWarning that otherwise is raised since Python 3.12 for these methods.

Use timezone-aware datetime objects

---

social_core/backends/azuread.py

`AzureADOAuth2` uses the v1.0 API which doesn't support personal accounts. Updating the endpoints used by the original class may break backward compatibility, so add this as just an additional subclass.
This should also fix #723

Add AzureADOauth2 backend using the v2.0 API.

---

social_core/backends/atlassian.py
social_core/tests/backends/test_atlassian.py

Remove usage `name` in favor for `accountId` for Atlassian backend. Fixes [Issue 517](https://github.com/python-social-auth/social-core/issues/517) - essentially a `KeyError` when trying to access `name`.
Atlassian deprecation notice 1 October 2018:
> By 29 April 2019, we will remove personal data from the API that is used to identify users, such as `username` and `userKey`, and instead use the Atlassian account ID (`accountId`). Additionally, will be restricting the visibility of other personal data, such as email, in conjunction with a user's profile privacy settings.
Further down in the same deprecation notice:
Field | Change | Nullable | Notes
-- | -- | -- | --
name | REMOVED | N/A | Use accountId instead.
_Put an `x` in the boxes …

Fix deprecated Atlassian field `name`

---

social_core/backends/linkedin.py
social_core/tests/backends/test_linkedin.py

This is a follow-up to and addition onto https://github.com/python-social-auth/social-core/pull/915
All that the preceding PR includes is part of it, plus tests passing. Props to @MohamedAhmed412000 for the initial work
It'll supersede #915 and #934

Add passing tests for linkedin OAuth updates

---

social_core/storage.py
social_core/tests/backends/test_dummy.py

The dummy tests were failing on my non-UTC development machine, because the timestamps were generated with mktime(), which uses the locale settings from the host. Changing this to use the timezone-aware `now` sorted it.
Extracted from https://github.com/python-social-auth/social-core/pull/951 by @offbyone
your code._

Modify the dummy tests to be timezone-safe

---

.github/workflows/release.yml

- use uv to build and publish packages
- use trusted publishing instead for stored token (currently not setup, waiting for @omab with this)
- build and lint packages on every commit, not only on release time
your code._

feat: modernize release process

---

social_core/backends/evernote.py
social_core/backends/facebook.py
social_core/backends/jawbone.py
social_core/backends/oauth.py
social_core/backends/open_id.py
social_core/backends/twitter.py
social_core/backends/vk.py
social_core/backends/weixin.py
social_core/pipeline/social_auth.py
social_core/utils.py

chore: remove not needed else statement

---

social_core/backends/base.py
social_core/backends/lastfm.py
social_core/backends/yahoo.py
social_core/tests/backends/test_livejournal.py
social_core/tests/backends/test_ngpvan.py
social_core/tests/backends/test_open_id_connect.py
social_core/tests/backends/test_steam.py

Better to use f-strings or triple quoted strings.
your code._

chore: avoid using join on string literals

---

pyproject.toml
social_core/backends/classlink.py
social_core/backends/clever.py
social_core/backends/digitalocean.py
social_core/backends/discord.py
social_core/backends/docker.py
social_core/backends/drip.py
social_core/backends/fitbit.py
social_core/backends/google.py
social_core/backends/mineid.py
social_core/backends/paypal.py
social_core/backends/pocket.py
social_core/backends/podio.py
social_core/backends/shimmering.py
social_core/backends/slack.py
social_core/backends/twitch.py
social_core/backends/twitter_oauth2.py

chore: use f-strings where applicable

---

social_core/utils.py

Logging the response text for an `HTTPError` greatly improves the developer's ability to figure out what might going wrong with an integration.

Log `HTTPError` response text

---

social_core/backends/azuread_b2c.py

fixes #809.
The Authority Host can be defined to be a custom domain as well using front door in Azure. With this, the tenant name is not prefixed to the authority host in the base url.
We update this by prefixing the tenant name with the default authority host only if the authority host is not defined.

fix: update Azure B2C base URL to allow custom domains

---

pyproject.toml
social_core/backends/google_onetap.py
social_core/tests/backends/test_google.py

The changes adds Google One Tap as a backend
You can test the changes with this dummy project https://github.com/kviktor/django-onetap-example
I haven't yet added tests or documentation but if the changes look okay I'll add them too.
I have 2 questions tho I'm not exactly sure about, maybe someone can help out
- I've added google-auth as a dependency, technically it's just downloading Google's cert files then verifying the jwt token however I didn't want to reimplement the wheel for it and it's a bit safer this way imo
- as it requires a new dependency I've added a new Python module for it, is that ok? (I can move it into `google.py` with catching ImportError and raising an exception if the library is missing in the class)
Docs at https://github.com/python-social-auth/social-docs/pull/256

Google One Tap implementation

---

social_core/backends/discourse.py
social_core/backends/open_id_connect.py

fix: corrected backeds nonce interface

---

social_core/storage.py

Also:
- Improve annotation of `PartialMixin.data`
- Remove unused `user` attribute of `UserMixin`, which may create type annotation conflicts in derived classes: https://github.com/galaxyproject/galaxy/issues/19617
your code._

Fix ``PartialMixin.next_step`` type annotation

---

social_core/backends/fedora.py
social_core/tests/backends/test_fedora.py

Fedora Infrastructure is deprecating the OpenID login method, soon it will stop working.
Ref: https://fedoramagazine.org/end-of-openid-authentication-in-fedora-account-system/

Add the OpenIdConnect-based backend for Fedora, and deprecate the OpenID-based one

---

social_core/backends/linkedin.py
social_core/tests/backends/test_linkedin.py

The previous PR #950 mistakenly replaced the OAuth2 endpoint with the OpenID Connect one. Users who use OpenID Connect should use `LinkedinOpenIdConnect`. For existing LinkedIn OAuth2 users like myself, `LinkedinOAuth2` should still work. 
Just to clarify: LinkedIn has **NOT** removed the `r_liteprofile` scope for OAuth2 users — it's still functioning properly. If anyone is having issues with scopes, please check the “Products” tab in your LinkedIn App Setup page.
For example, here we have both OAuth2 and OpenID Connect enabled:

Revert LinkedIn OAuth2

---

social_core/backends/okta.py
social_core/tests/backends/test_okta.py

your code._
Should fix #662 without breaking non-custom auth server configurations.

Bug/okta OIDC configuration url fix

---

social_core/backends/base.py
social_core/backends/oauth.py
social_core/backends/open_id.py
social_core/backends/saml.py
social_core/exceptions.py
social_core/strategy.py

When cookies are created with SameSite policy, they won't be available during the authentication flow which uses POST such as OpenID or SAML. This adds support in Strategy to get session ID and restore it later in the login flow.
See https://github.com/python-social-auth/social-app-django/issues/481

feat: implement session restore when cookies are not reliable

---

social_core/backends/keycloak.py

Fixes #1102 by adding support for a `JWT_LEEWAY` setting in the Keycloak backend.

feat: Add JWT leeway setting to KeycloakOAuth2 backend

---

social_core/backends/soundcloud.py
social_core/tests/backends/test_soundcloud.py

**Title**: Fix SoundcloudOAuth2 to Use Authorization Header and Update Tests
**Description**:
This PR fixes a `401 Unauthorized` error in the `SoundcloudOAuth2` backend caused by an outdated `user_data` method. SoundCloud API now requires an `Authorization: OAuth <access_token>` header instead of passing `oauth_token` as a query parameter, as noted in their security updates: https://developers.soundcloud.com/blog/security-updates-api. The PR also updates the test suite to reflect these changes and adds a new test for the `user_data` method.
**Changes**:
- Updated `user_data` method in `social_core/backends/soundcloud.py` to use the `Authorization` header and change the endpoint from `/me.json` to `/me`.
- Updated `social_core/tests/backends/test_soundcloud.py` to use the new endpoint …

Fix SoundcloudOAuth2 user_data to use Authorization header and update test

---

social_core/backends/auth0_openidconnect.py
social_core/tests/backends/test_auth0_openidconnect.py

I have been using the generic OIDC backend for Auth0 and it more or less works, so I don't think too many changes are required from the generic OIDC backend. However, I'm running into issues with the provider name etc. that that I think would be solved by having an auth0 specific implementation.
Please let me know what else would be required in terms of tests etc., I need to do a bit of further testing of the refresh tokens.

Auth0 OIDC backend

---

social_core/backends/vk.py
social_core/tests/backends/test_vk.py

VK has started sending out such a message to everyone who has OAuth integration:
Eng translation:
> VKontakte switches to a domain vk.ru - now all API integrations and authorizations will be available only through it.
> 
> To ensure that your services work correctly, change their domains by September 30th, for example:
> - vk.ru/dev instead of vk.com/dev
> - oauth.vk.ru instead of oauth.vk.com
> - api.vk.ru instead of api.vk.com
> 
> If you have any questions, please contact Support: dev.vk.com/ru/support

Change domains for VK backend

---

social_core/backends/open_id_connect.py

Dear developpers,
When using the OpenIdConnectAuth class with a ADFS IdP I got an issue because the email and `USERNAME_KEY` was not part of the response but part of the id_token.
The changes I made propose to use the info from the id_token if the key is not present in the response.
I don't know if this makes sense or if this should be a new Class.
I don't know how to make a test for this.

OIDC: use info in id_token if not in response

---

social_core/backends/asana.py
social_core/backends/azuread.py
social_core/backends/base.py
social_core/backends/behance.py
social_core/backends/disqus.py
social_core/backends/evernote.py
social_core/backends/exacttarget.py
social_core/backends/itembase.py
social_core/backends/oauth.py
social_core/backends/odnoklassniki.py
social_core/backends/open_id.py
social_core/backends/persona.py
social_core/backends/pocket.py
social_core/backends/saml.py
social_core/backends/shopify.py
social_core/backends/telegram.py
social_core/pipeline/social_auth.py
social_core/storage.py

The pipeline can be customized to contain any arbitrary data and that could result in passing duplicate parameters to the extra_data method. Passing the pipeline kwargs in a separate dict avoids that. Passing positional args is dropped as that can break in various ways.
This is possibly a breaking change for third-party backends.

fix(backens): avoid passing pipeline data as kwargs
