python-social-auth/social-core

social_core/backends/asana.py
social_core/tests/backends/test_asana.py

Bugfix: Correctly handle the asana user response

---

social_core/backends/saml.py

Instead of passing dummy IDP settings to `OneLogin_Saml2_Settings` we can use  `sp_validation_only`. That would enable us to set values of `SECURITY_CONFIG` in SP metadata xml.
@omab could you please review this?

removed IDP dummy settings while generating metadata xml

---

social_core/backends/mediawiki.py

If anyone would like to test the backend send me an email. I have a auth-only test application on English Wikipedia and can share the key and secret. It would be good to review the data written to the database and the security and correctness of the pipeline.

Add mediawiki backend

---

social_core/backends/facebook.py

expires is replaced with expires_in in facebook backend #31

---

social_core/actions.py
social_core/tests/actions/actions.py

(There are some others but it requires X to be "true" so unwilling to
change)
Signed-off-by: Chris Lamb <chris@chris-lamb.co.uk>

Use "X if Y else Z" over difficult to read quickly "Y and X or Z".

---

social_core/storage.py

This PR refers to [this Issue](https://github.com/python-social-auth/social-app-django/issues/17).
It is missing tests (@omab I need some help on how to do it if it is even possible).

add get_access_token method

---

social_core/backends/monzo.py

Signed-off-by: Chris Lamb <chris@chris-lamb.co.uk>

Add Monzo authentication backend.

---

CHANGELOG.md
social_core/backends/monzo.py

remove the incorrect import pointing to social.auth

use relative path in import BaseOAuth2

---

social_core/backends/orcid.py

Implemented ORCID OAuth 2 backend (https://orcid.org/) and its sandbox option. Separately doing a pull request for the documentation in social-docs.

Implemented ORCID backend

---

social_core/backends/vk.py

The current solution is not working for me. I am always getting empty results here https://github.com/python-social-auth/social-core/blob/master/social_core/backends/vk.py#L136 
and it fails with error because the return of the function is None.

Speed up authorization process for VKAppOAuth2.

---

social_core/actions.py

Apply same sanitization as on connect to disconnect.

Sanitize disconnect URLs as well

---

social_core/pipeline/user.py

Don't change user fields if they changed.
This pr prevents situation: user edited his profile and it was replaced by social-auth.
Also made it more readable.

Don't change if current_value defined

---

social_core/backends/microsoft.py

Added backend to support login with a user account from login.microsoftonline.com/ using the newer oauth2 v2.0 API to allow access to graph.microsoft.com.

Added backend to support microsoft graph login

---

social_core/backends/openshift.py

add openshift oauth2 backend support

---

social_core/storage.py

Issue #128 fixed. Replaced fromtimestamp to utcfromtimestamp

Fixed issue #128 with expiration_timedelta calculation.

---

social_core/backends/reddit.py

I had an unauthorized for https://ssl.reddit.com/api/v1/access_token that was solved by this change.

reddit wants authorization at token stage

---

CHANGELOG.md
social_core/backends/coinbase.py
social_core/tests/backends/test_coinbase.py

Current implementation seems to be broken. https://developers.coinbase.com/api/v2#show-a-user

Fix coinbase backend to use api v2

---

social_core/backends/facebook.py

Update Facebook backend REDIRECT_STATE to False

---

social_core/backends/chatwork.py
social_core/tests/backends/test_chatwork.py

Add backend chatwork #161

---

CHANGELOG.md
social_core/backends/linkedin.py

Move oauth_token to Request Header

---

social_core/backends/eveonline.py

ExpiresOn is replaced with expires_in in eveonline backend

---

social_core/backends/kakao.py

This commit resolve #171 
I think it improve code stability👻

Add "profile_image" and "thumbnail_image"

---

social_core/backends/line.py

Line Login V1 has been abolished.
Therefore, I updated it to match the latest version of LINE Login v2.1.
https://developers.line.me/en/docs/line-login/web/integrate-line-login/

Updated to LINE Login v2.1

---

social_core/backends/globus.py
social_core/tests/backends/test_globus.py

Globus Auth is a foundational identity and access management platform service designed to address unique needs of the science and engineering community. Globus provides cloud-based services for reliably moving, sharing, publishing and discovering data, whether your files live on a supercomputer, lab cluster, tape archive, public cloud, or your own laptop.
https://globus.org
https://docs.globus.org
https://developers.globus.org

Add Globus OpenID Connect backend

---

social_core/backends/discord.py

Discord backend

---

social_core/utils.py

we got some malicious redirect on our app. this need to be fixed ASAP.

social-core#62: sanitizing urls like `///evil.com`

---

social_core/backends/coinbase.py

https://developers.coinbase.com/docs/wallet/coinbase-connect/integrating

Update access token url + authorize url

---

social_core/backends/base.py
social_core/backends/beats.py
social_core/backends/facebook.py
social_core/backends/jawbone.py
social_core/backends/justgiving.py
social_core/backends/legacy.py
social_core/backends/persona.py
social_core/backends/twilio.py
social_core/backends/weixin.py
social_core/backends/yahoo.py

This typo was repeated / copy & pasted to several places.

Fix docstring typos: loging → login

---

requirements-openidconnect.txt
social_core/backends/open_id_connect.py

Use jose library for JWK instead of the abandoned jwkest
Use self.request to allow for options such as certs
Updated requirements for openid connect

Fixes in Open ID Connect

---

CHANGELOG.md
social_core/backends/auth0.py

Hi all, this is my first submission - I wanted to add  provider for Auth0, which I will need in an existing app called Weblate (http://weblate.org). I think it makes sense to make a contribution here, since it might be useful also for others.
Code is actually from: https://auth0.com/docs/quickstart/webapp/django/01-login
PS: This is my first contact with Django framework, so I'm not really 100% confident if I did all correct.

WIP: Added Auth0 provider

---

social_core/backends/elixir.py

This merge request is inspired by Galaxy-AAI integration efforts.  Refer to  pull request https://github.com/galaxyproject/galaxy/pull/7535  for more context

remove profile from default-scope and ignore at_hash verification

---

social_core/backends/strava.py

Add scope separator for strava

Add scope separator for strava

---

social_core/pipeline/utils.py

- check if id attribute exists the user object  before assigning it to `kwargs`
- fixes Issue #365 
- #365

Check for id attribute in user object 

---

social_core/backends/cognito.py

Use the value from family_name attribute for last_name in Cognito backend

---

setup.cfg
social_core/tests/requirements-base.txt
tox.ini

Initial pr that just switches the test runner to pytest, leaving all
tests. All tests are found and pass. We can then gradually start using
pytest features.

switch to pytest

---

social_core/backends/saml.py

Heavily based on the code provided by Diego Allen in his bug report.
Closes: #199

Support SAML single logout

---

CHANGELOG.md
social_core/backends/untappd.py

See Untappd ticket: https://help.untappd.com/public/tickets/84aa71d728c27c2c7200ed57f37e37c60eb1dc16dbe606354d6f183f80143dcd

Always send a User Agent value for the Untappd backend.

---

social_core/backends/naver.py
social_core/tests/backends/test_naver.py

Ready to prevent API deprecation for backends.naver

---

social_core/backends/twitch.py
social_core/tests/backends/test_twitch.py

Resolves #386 
---
Changed authorization and access token URLs also verified and actualised `user_data` structure in test.

Migrate Twitch v3 → v5 (fix #386)

---

.gitignore
CHANGELOG.md
social_core/backends/simplelogin.py
social_core/tests/backends/test_simplelogin.py

SimpleLogin.io is a social login provider that focus on user privacy.
This is my first PR in this project, please let me know if you need any additional information! Another PR will be created in https://github.com/python-social-auth/social-docs to add SimpleLogin doc.

Add SimpleLogin backend

---

social_core/tests/requirements-base.txt
social_core/tests/requirements-pypy.txt
social_core/tests/requirements-python2.txt
social_core/tests/requirements-python3.txt

Fix pytest dependency for python2.7

---

requirements-base.txt
social_core/backends/apple.py
social_core/tests/backends/test_apple.py

Hi!
I've implemented Sign In With Apple backend and tested it with both web and mobile applications. Hope this might be useful.
Resolves #370.

Implement Sign In With Apple backend

---

social_core/backends/kakao.py
social_core/tests/backends/test_kakao.py

[URGENT] kakao v1 -> v2

---

CHANGELOG.md
social_core/backends/patreon.py
social_core/tests/backends/test_patreon.py

https://github.com/python-social-auth/social-core/issues/307 has been an open issue for over a year, and I'd like to use it for a project so I fixed it. Tested with my account and it has appeared to work, but the travis tests fail. Will look at them and see if I can update it.

Update Patreon per issue #307

---

.travis.yml

See: https://tox-travis.readthedocs.io/en/stable/

Use travis-tox to simplify travis/tox interaction.

---

social_core/backends/github.py

I will open a documentation PR as well to document when and how this should be used!

Add GithubAppAuth backend. Fix #411, #111

---

social_core/backends/okta.py

Issue: https://github.com/python-social-auth/social-core/issues/458
your code._

Fix email response gathering

---

social_core/tests/backends/open_id_connect.py
social_core/tests/backends/test_vk.py
social_core/tests/models.py
social_core/utils.py

Rebased version of #424 by @tirkarthi (closed by stale[bot]). Fixes #423 (closed by stale[bot]).
* Avoid deprecated `base64.encodebytes`, removed in Python 3.9.
* Avoid deprecated invalid escape sequences in string literal, which will eventually be a syntax error.
* Avoid deprecated `collections.Callable`, removed in Python 3.9.

Add Python 3.9 compatibility

---

CHANGELOG.md
social_core/backends/base.py

Connected to https://github.com/python-social-auth/social-core/issues/474

Send proxies in request

---

social_core/backends/apple.py

Improve error handling in the Apple backend

---

CHANGELOG.md
social_core/backends/zoom.py
social_core/tests/backends/test_zoom.py

Add Zoom backend support. Fixes #478.
your code._

Added Zoom OAuth backend support

---

social_core/backends/yahoo.py

The OpenID service was terminated on 2/20/2020.
your code._
See https://s.yimg.com/wm/mbr/html/openid-eol-0.0.1.html

Drop YahooOpenId

---

social_core/backends/amazon.py

Receiving 503 error when pulling profile from www server with a "pythonrequest" user-agent.  Updated to use api subdomain as directed by Amazon documentation (https://developer.amazon.com/docs/login-with-amazon/obtain-customer-profile.html).

Update Amazon to use api URL for user_data pull

---

social_core/backends/fence.py
social_core/tests/backends/test_fence.py

Implement an OIDC-based backend of [uc-cdis/fence](https://github.com/uc-cdis/fence). 
your code._

Implement an OIDC-based backend for uc-cdis/fence

---

social_core/backends/azuread_tenant.py

Fixes Azure Access Directory Tenant server error 500 - Unable to load certificate
https://github.com/python-social-auth/social-core/issues/486
your code._

Fix Azure AD Tenant - Unable to load certificate

---

.github/matchers/flake8.json
.github/workflows/flake8.yml

It lints code base with flake8 and adds GitHub annotations for errors.
There are currently lots of errors raised. I can fix the code as well, given there is consensus this is the right coding style tool (and probably after merging other pending pull requests to avoid excessive merge conflicts).
your code._
Discussed in https://github.com/python-social-auth/social-core/issues/445

Add flake8 GitHub action

---

.github/workflows/test.yml
README.md

This PR adds Github Actions as CI option and run tests on it, thus makes it easy to contribute because it runs faster and better integrated with GitHub. Please see https://github.com/dulmandakh/social-core/actions
FYI: I would like to contribute to social-core, especially on CI like automatic publishing, lint etc...
@omab please review and merge.
- [x ] Other (please describe): add CI option
your code._

github actions test and badge

---

.github/workflows/flake8.yml

Use only major version of GitHub Actions so that we receive major and patch updates automatically. 
your code._

use major version of GH actions

---

social_core/backends/oauth.py

The previous Docstring was miss understanding when it says:
- "Setting name is created from current backend name (all uppercase) plus _EXTRA_DATA." which leads to <uppercase_current_backend>_EXTRA_DATA.
I'm proposing this change to explicitly include the SOCIAL_AUTH_ prefix on the Setting entry, which leads to SOCIAL_AUTH_<uppercase_current_backend>_EXTRA_DATA.
Also I've tested and just EXTRA_DATA but I understand that its too generic.
the PR. If you're unsure …

Update OAuthAuth Class Docstring

---

CHANGELOG.md
requirements-base.txt
social_core/backends/khanacademy.py
social_core/backends/mediawiki.py
social_core/backends/nk.py
social_core/backends/oauth.py
social_core/backends/shopify.py
social_core/backends/xing.py
social_core/pipeline/utils.py
social_core/storage.py
social_core/tests/backends/open_id_connect.py
social_core/tests/models.py
social_core/tests/test_storage.py
social_core/utils.py

Remove six package from dependency and replace its usages.
your code._

remove six usage and dependency

---

social_core/backends/apple.py

Multiple scopes separated in query string parameter by a space encoded as `%20` not `+`.
your code._
Related issue: https://github.com/python-social-auth/social-core/issues/470

Change default scope separator for apple

---

social_core/pipeline/social_auth.py

The integrity error also could mean something else than duplicate entry and
it should be reraised in that case.
your code._
Discovered in https://github.com/WeblateOrg/weblate/issues/4832

Improve handling of integrity errors in pipeline

---

requirements-openidconnect.txt

It is already present in requirements-base.txt.
See #503
your code._

deps: Remove duplicate PyJWT dependency

---

.coveragerc
.github/workflows/test.yml

Little clean-up of the GitHub workflow and added submission of coverage reports to CodeCov.
your code._

Submit coverage reports to CodeCov

---

setup.py
social_core/tests/requirements-base.txt
social_core/tests/requirements-pypy.txt
social_core/tests/requirements-python2.txt
social_core/tests/requirements-python3.txt
social_core/tests/requirements.txt
tox.ini

Keep only separate requirements for PyPy (though I have no clue
whethere it is still useful).
your code._

tests: Simplify test requirements

---

.github/workflows/test.yml

With buffering the not completed tests might be invisible in GitHub log.
your code._

ci: Avoid Python output buffering

---

social_core/tests/actions/actions.py
social_core/tests/backends/base.py
social_core/tests/backends/test_apple.py
social_core/tests/backends/test_broken.py
social_core/tests/backends/test_saml.py
social_core/tests/backends/test_utils.py
social_core/tests/requirements-pypy.txt
social_core/tests/requirements.txt
social_core/tests/test_exceptions.py
social_core/tests/test_partial.py
social_core/tests/test_storage.py
social_core/tests/test_utils.py

It should not be needed on supported Python versions.
your code._

deps: Drop unittest2 and mock

---

social_core/backends/dropbox.py
social_core/tests/backends/oauth.py
social_core/tests/backends/test_dropbox.py

It has been shut down in 2017.
It has been shut down in 2017.
your code._

backends: Drop support for no longer working Dropbox v1 API

---

social_core/backends/yahoo.py

Rebased https://github.com/python-social-auth/social-core/pull/512 originally by @lavender15963j
your code._

fixed yahoo login

---

social_core/backends/osso.py
social_core/tests/backends/test_osso.py

I maintain an open source project [Osso](https://github.com/enterprise-oss/osso) that's a web service that wraps SAML SSO in an OAuth 2.0 authorization code grant flow. The Osso admin UI allows you to onboard SAML SSO tenants, generates SAML config docs for leading identity providers, and handles the SAML authentication, allowing you to consume normalized user profiles through an OAuth flow.
While this library has support for SAML, Osso goes a step further to handle the extra 10% - persistence, UI and documentation, so we hope you'll consider the PR. 
I've never written Python before this, so struggled a bit and am very open to feedback.
I don't actually know how to run the linter here? I did the following and it reported a massive …

Add backend Osso

---

social_core/backends/azuread_tenant.py

This adds the default values of `jwks_url` and `open_configuration_url` containing v2.0 to AzureADV2TenantOAuth2 class
- [ X] Bugfix (non-breaking change which fixes an issue)
- [ X] Refactoring (no functional changes, no api changes)
your code._
- [x ] Lint and unit tests pass locally with my changes
_There's currently no testing on the Azure AD Tenant classes, but they go through Azure AD, which still passes_ 
the …

default v2.0 jwks_url and open_configuration_url to AzureADV2Tenant

---

CHANGELOG.md

Some changes are not described in the changelog. I should probably have done that when merging the pull requests...
your code._

docs: Document changes

---

CHANGELOG.md

Basically a fixup for https://github.com/python-social-auth/social-core/pull/572
your code._

Docs: Add missing changelog header

---

social_core/backends/facebook.py

Just decorator @handle_http_errors was added to avoid raising of http errors

decorator @handle_http_errors was added over .do_auth() (#579)

---

social_core/backends/cilogon.py
social_core/tests/backends/test_cilogon.py

- [x ] New feature (non-breaking change which adds functionality)
your code._
- [ x] Lint and unit tests pass locally with my changes
- [ x] I have added tests that prove my fix is effective or that my feature works
--

Ci logon backend

---

social_core/tests/backends/base.py
social_core/tests/backends/open_id.py
social_core/tests/backends/test_amazon.py
social_core/tests/backends/test_github.py
social_core/tests/backends/test_github_enterprise.py
social_core/tests/backends/test_livejournal.py
social_core/tests/backends/test_ngpvan.py
social_core/tests/backends/test_yahoo.py

This PR aims to the "Too many open files" issue originally, which blocks me to run tests locally and build the Fedora package. Other included fixes were found after I succeeded in running all tests.

Fix several issues in tests, especially the "Too many open files" issue.

---

.github/workflows/test.yml

Otherwise the packages list can be outdated and packages no longer
existing.
your code._

ci: Run apt-get update prior installing packages

---

social_core/backends/shopify.py

The old one is no longer supported, see https://github.com/python-social-auth/social-docs/pull/87
your code._

shopify: Update API version

---

CHANGELOG.md
social_core/backends/microsoft.py
social_core/tests/backends/test_microsoft.py

fix microsoft login error

---

social_core/backends/vk.py

vkontakte: Update API version

---

social_core/backends/vk.py

Update vk backend to the latest api. More info here: https://vk.com/dev/versions
Just bump to new version.
your code._
Just bump to new version.

Update vk backend to the 5.131

---

social_core/backends/azuread.py

Using upn is wrong as it contains tags for external users.
Fixes #627
your code._

backeds: Fix getting e-mail from Azure

---

social_core/backends/azuread.py

The e-mail is not provided for managed users, but it usually
matches UPN. This was also the previous behavior prior #629.
your code._

backends: Fallback to UPN for email in Azure

---

social_core/backends/open_id_connect.py
social_core/tests/backends/oauth.py
social_core/tests/backends/open_id_connect.py
social_core/tests/backends/test_elixir.py
social_core/tests/backends/test_fence.py
social_core/tests/backends/test_globus.py
social_core/tests/backends/test_google.py
social_core/tests/backends/test_okta.py
social_core/tests/backends/test_open_id_connect.py
social_core/tests/backends/test_twitch.py
social_core/utils.py

Fixes https://github.com/python-social-auth/social-core/issues/591. It fixes how kid's are used to fetch the correct keys (especially when keys are rotating).
your code._

Fix kid key rotation for OpenID Connect

---

social_core/backends/gae.py
social_core/backends/pinterest.py
social_core/backends/professionali.py
social_core/backends/slack.py
social_core/backends/vk.py
social_core/backends/weibo.py
social_core/backends/weixin.py
social_core/tests/backends/open_id.py
social_core/tests/backends/test_auth0.py
social_core/tests/backends/test_discourse.py
social_core/tests/backends/test_open_id_connect.py
social_core/tests/backends/test_saml.py
social_core/tests/backends/test_vk.py

- remove no longer needed future imports
- remove no longer necessary coding header
your code._

pyupgrade: Remove not needed future imports

---

social_core/backends/oauth.py
social_core/backends/odnoklassniki.py
social_core/backends/utils.py
social_core/pipeline/user.py
social_core/pipeline/utils.py
social_core/storage.py
social_core/tests/backends/test_discourse.py
social_core/tests/backends/test_saml.py

- use dict comprehensions
- define sets directly
- use generators when applicable instead of comprehesions
your code._

pyupgrade: Use modern comprehensions

---

social_core/backends/facebook.py
social_core/tests/backends/test_bitbucket.py
social_core/tests/backends/test_ngpvan.py
social_core/tests/backends/test_slack.py

These are no longer necessary in Python 3.
your code._

pyupgrade: Remove u prefix from unicode literals

---

social_core/backends/apple.py

I propose add new log in apple backend, because AuthFailed raise in [this line](https://github.com/python-social-auth/social-core/blob/eb2010b542e7a5963caca291cce8a4caee23a09b/social_core/backends/apple.py#L132) , I don't know  which is error generate in this point
your code._
Screenshots:

print error in apple backend

---

social_core/backends/professionali.py
social_core/backends/vk.py
social_core/tests/backends/test_saml.py

- use OSError instead of IOError
- remove not needed r argument to open()
your code._

pyupgrade: Upgrade legacy code

---

setup.py

- use OSError instead of IOError
- remove no longer needed coding
- utilize f-string
your code._

pyupgrade: Upgrade setup.py

---

.pre-commit-config.yaml

It can be extended in the future to include more code formatting tools. This is very minimal configuration to introduce the service. 
To use [pre-commit.ci](https://pre-commit.ci/) the application access has to be approved by @python-social-auth admin (@omab), I've already sent request for that.
your code._

ci: Add pre-commit.ci configuration

---

social_core/backends/facebook.py

The current version is 12.
your code._

facebook: Fix Facebook api version

---

social_core/backends/azuread.py
social_core/backends/azuread_b2c.py
social_core/backends/azuread_tenant.py

Currently the public Azure authority host URL (login.microsoftonline.com) is hard coded in all of the Azure backends. However, Azure has multiple authority hosts (see https://docs.microsoft.com/en-us/python/api/azure-identity/azure.identity.azureauthorityhosts?view=azure-python) so in order to work with all of them the authority host URL needs to be configurable. These changes keep the public authority host as the default, but introduce a setting `AUTHORITY_HOST` to be able to override the default. …

Support all Azure Authority Hosts

---

social_core/backends/musicbrainz.py
social_core/tests/backends/test_musicbrainz.py

backends: Add MusicBrainz OAuth2

---

social_core/backends/grafana.py
social_core/tests/backends/test_grafana.py

Adds Grafana Oauth2 backend.
your code._

Add Grafana backend

---

social_core/backends/kakao.py

#696 Kakao login integration issue has been resolved. This issue urgently needs a patch.
your code._
before:
```
[2022-07-27 17:50:16,091] ERROR in app: Exception on /complete/kakao/ [GET]
Traceback (most recent call last):
File "/home/jiho/.virtualenvs/flask2nd/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
response = self.full_dispatch_request()
File …
```

Fixed an error that occurred because there were no items to collect when performing Kakao login

---

.github/workflows/flake8.yml
.github/workflows/release.yml
.github/workflows/test.yml

The setup-python action supports caching pip wheels, so utilize that for
iproved performance.
your code._

ci: Cache pip wheels

---

.github/workflows/flake8.yml
.github/workflows/test.yml
.pre-commit-config.yaml
.travis.yml
docker-compose.yml

Add YAML formatter to pre-commit. This is the style that causes smallest diff.
your code._

pre-commit: Format yaml files

---

.pre-commit-config.yaml

The flake8 was kept out as the code is not yet ready.
your code._

pre-commit: autoupdate

---

.pre-commit-config.yaml

All issues were fixed in https://github.com/python-social-auth/social-core/pull/707
your code._

pre-commit: Update flake8 to 5.0.4

---

social_core/backends/amazon.py
social_core/backends/pinterest.py

It is deprecated for years and there is now no good reason to override SSL defaults here.
Fixes #713
your code._

backends: Remove usage for TLSv1

---

.github/workflows/test.yml

Also add Python 3.11 to the test matrix.
your code._

ci: Pin test image to Ubuntu 20.04 for Python 3.6 support

---

setup.cfg
social_core/tests/backends/test_vault.py

fix flake8(E501)

---

social_core/backends/seznam.py
social_core/tests/backends/test_seznam.py

Adds Seznam OAuth2 backend
your code._
Documentation PR: https://github.com/python-social-auth/social-docs/pull/130
Tested using patched DefectDojo instance: https://github.com/nightshiba/django-DefectDojo/tree/add-seznam-backend#test

backends: Add Seznam OAuth2

---

.github/workflows/test.yml
tox.ini

ci: Test in Python 3.11

---

CHANGELOG.md
social_core/backends/facebook.py
social_core/tests/backends/test_facebook.py
social_core/tests/backends/test_open_id_connect.py

This adds a new backend for Facebook Limited Login
This is a new login method for Facebook which uses OpenID Connect and doesn't have the ability to associate a user logging into one app with the IDFA token on iOS devices: https://developers.facebook.com/docs/facebook-login/limited-login.
your code._

Add Facebook Limited Login backend

---

.landscape.yaml

Landscape CI is no longer being used

---

.github/workflows/flake8.yml
.github/workflows/test.yml

Deal with the 6 warnings on GitHub Action runs...
* https://github.com/python-social-auth/social-core/actions/runs/4273992152
https://github.com/codecov/codecov-action#migration-from-v1-to-v3
your code._
the component looks …

Upgrade GitHub Actions

---

.github/dependabot.yml

ci: Enable dependabot to automate github actions version upgrades

---

social_core/backends/clef.py
social_core/backends/google.py
social_core/backends/saml.py
social_core/pipeline/user.py
social_core/tests/backends/oauth.py
social_core/utils.py

https://beta.ruff.rs/docs/rules/#flake8-simplify-sim
your code._

Simplify Python code with ruff --select=SIM --fix .

---

social_core/backends/azuread_tenant.py

azure: Fix typo in JWKS URL

---

social_core/backends/keycloak.py

I had somme difficulties using social-core with keycloak 20.0.3 following the instrauctions.
In particular, I got the following exception : `jwt.exceptions.InvalidAudienceError: Invalid audience`.
Taking hints from https://github.com/SwissDataScienceCenter/renku-gateway/issues/90, and introducing the changes mentioned in the added instructions of this commit (not tested on keycloak 21+), the setup now works.
your code._
the …

Fix the documentation for keycloak 20.0* and more

---

social_core/backends/twitter_oauth2.py
social_core/tests/backends/test_twitter_oauth2.py

fix - https://github.com/python-social-auth/social-core/issues/792
Add a new backend for Twitter OAuth2 backend.
https://developer.twitter.com/en/docs/authentication/oauth-2-0/authorization-code
Document for social-doc - https://github.com/python-social-auth/social-docs/pull/150
your code._
Twitter API v2 OAuth authentication utilizes PKCE (Proof Key for Code Exchange), and the TwitterOAuth2 class I implemented contains code to support this specification (The code included in …

Add Twitter OAuth2 backend

---

social_core/backends/uffd.py

Adds a new backend to support uffd single sign on - https://git.cccv.de/uffd/uffd
As there are multiple uffd installations, the base URL is configured through config not code.
your code._

add uffd oauth2 backend

---

social_core/backends/ping.py

New backend for [ping identity](https://www.pingidentity.com/en.html).
your code._

New ping identity OIDC backend.

---

.github/workflows/test.yml
.pre-commit-config.yaml
docker-compose.yml
setup.py
tox.ini

Add support and tests for Python 3.12
your code._

Support Python 3.12

---

social_core/backends/discogs.py
social_core/tests/backends/test_discogs.py

This PR introduces a new backend for connecting via the Discogs API - https://www.discogs.com/developers/
your code._

Create a backend for OAuth1 connection to Discogs

---

CHANGELOG.md
social_core/backends/keycloak.py

Reverts python-social-auth/social-core#815
Fixes #854

Revert "Make Keycloak's ID_KEY configurable"

---

social_core/backends/etsy.py
social_core/tests/backends/test_etsy.py

- Resolves Issue: https://github.com/python-social-auth/social-core/issues/872
- Added a new backend: `EtsyOAuth2`
- Inherits `BaseOAuth2PKCE` for backend and `OAuth2PkceS256Text` for tests.
- Added docs here: https://github.com/python-social-auth/social-docs/pull/199

feat: Added Backend 'EtsyOAuth2'

---

social_core/backends/linkedin.py

Linkedin [supports refresh_token](https://learn.microsoft.com/en-us/linkedin/shared/authentication/programmatic-refresh-tokens) for it's [Marketing API Program](https://learn.microsoft.com/en-us/linkedin/marketing/?view=li-lms-2024-01)
your code._

Add `refresh_token` into Linkedin `EXTRA_DATA`

---

tox.ini

It now breaks things instead of fixing them - both modules now ship wheels which are compatible.
your code._

tox: remove lxml/xmlsec workaround

---

social_core/backends/mediawiki.py

+AuthException at access_token
Errors can also occur at this step (in my case, I have been receiving signature failure errors). Without this exception, the library just returns a generic "NoneType object is not subscriptable" error and the OAuth error code is not displayed.
your code._

+AuthException at mediawiki.py' access_token

---

social_core/pipeline/social_auth.py
social_core/tests/backends/test_bitbucket_datacenter.py

It is stored as string in the database, so make conversion early.
Fixes https://github.com/python-social-auth/social-app-django/issues/568
your code._

pipeline: make sure uid is string

---

CHANGELOG.md
social_core/pipeline/user.py
social_core/tests/actions/actions.py
social_core/tests/test_pipeline.py

Allow overriding emails to be fully lowercase

---

.github/workflows/test.yml
pyproject.toml
tox.ini

chore: drop support for Python 3.8

---

social_core/tests/strategy.py
social_core/utils.py

This allows to join multiple lookups.
your code._

chore: use startswith with tuple

---

social_core/tests/test_utils.py

Python 2 is not supported for years, this was forgotten.
your code._

fix: remove outdated Python 2 code

---

social_core/backends/apple.py
social_core/backends/clever.py
social_core/tests/backends/oauth.py
social_core/tests/test_pipeline.py

chore: use next() instead of getting first element from list

---

social_core/backends/azuread_b2c.py
social_core/tests/backends/test_saml.py

chore: remove legacy code for no longer supported Python versions

---

social_core/actions.py
social_core/backends/mendeley.py
social_core/backends/oauth.py
social_core/backends/odnoklassniki.py
social_core/backends/professionali.py
social_core/backends/vk.py
social_core/utils.py

This directly contructs the list instead of using an intermediate copy.
your code._

chore: use unpacking instead of manual concatenation

---

social_core/pipeline/disconnect.py
social_core/tests/test_pipeline.py
social_core/tests/test_storage.py

chore: remove not needed params from exception class

---

social_core/tests/models.py

chore: use values when only dict values are needed

---

social_core/tests/backends/test_utils.py

chore: avoid import as when not renaming

---

social_core/backends/mailru.py
social_core/backends/open_id_connect.py
social_core/backends/professionali.py
social_core/backends/vk.py
social_core/tests/backends/test_open_id_connect.py

chore: use literals and comprehensions more effectively

---

social_core/backends/cognito.py
social_core/backends/discourse.py
social_core/backends/loginradius.py
social_core/backends/oauth.py
social_core/backends/open_id_connect.py
social_core/backends/orcid.py
social_core/backends/paypal.py
social_core/backends/untappd.py
social_core/backends/zoom.py
social_core/pipeline/mail.py
social_core/pipeline/social_auth.py
social_core/pipeline/user.py
social_core/storage.py
social_core/tests/pipeline.py

- do not use intermediate variables
- do not use useless else statements after return
your code._

chore: simplify return statements

---

social_core/backends/azuread_b2c.py
social_core/backends/azuread_tenant.py
social_core/tests/backends/test_saml.py

chore: bring back isort ordering

---

social_core/backends/base.py
social_core/backends/bungie.py
social_core/backends/saml.py
social_core/exceptions.py
social_core/tests/backends/test_linkedin.py

chore: remove not needed pass statements

---

social_core/tests/backends/oauth.py

chore: merge nested with statements

---

pyproject.toml
social_core/backends/bitbucket_datacenter.py
social_core/tests/backends/test_linkedin.py

There are still many to address, but this is a good starting point.
your code._

feat(ci): extend ruff rulesets

---

pyproject.toml
social_core/backends/grafana.py
social_core/backends/orcid.py
social_core/backends/saml.py
social_core/backends/slack.py
social_core/backends/weibo.py
social_core/pipeline/user.py
social_core/pipeline/utils.py

chore: apply assorted ruff fixes

---

social_core/backends/pocket.py

chore: build string directly instead of intermediate bits tuple

---

.github/workflows/release.yml

It is now stored in pyproject.toml.
your code._

fix(ci): correctly check for version info

---

social_core/backends/base.py
social_core/utils.py

This seems unused, and overriding SSL version seems weird these days.
your code._

chore: drop unused SSLHttpAdapter

---

.pre-commit-config.yaml
social_core/backends/email.py
social_core/backends/facebook.py
social_core/backends/saml.py
social_core/backends/vk.py
social_core/strategy.py
social_core/tests/backends/oauth.py
social_core/tests/backends/test_behance.py
social_core/tests/backends/test_disqus.py
social_core/tests/backends/test_foursquare.py
social_core/tests/backends/test_mapmyfitness.py
social_core/tests/backends/test_ngpvan.py
social_core/tests/backends/test_twitter.py
social_core/tests/backends/test_yahoo.py
social_core/tests/test_exceptions.py

chore(deps): update ruff to 0.9.0

---

.pre-commit-config.yaml
CHANGELOG.md
pyproject.toml
social_core/backends/base.py
social_core/backends/ngpvan.py
social_core/backends/professionali.py
social_core/backends/yahoo.py

feat(ci): introduce codespell

---

.github/renovate.json

feat: enable dependency dashboard for renovate

---

pyproject.toml
social_core/backends/cas.py

chore: use logging native formatting

---

.github/workflows/release-shared.yml
.github/workflows/release.yml

feat: make release flow reusable

---

pyproject.toml
social_core/backends/shopify.py

There is no need to delay importing and make it crash at usage time. Also add it to optional deps.
your code._

fix: import shopify API directly

---

CHANGELOG.md
pyproject.toml

chore: Version bump 4.5.5

---

social_core/backends/discourse.py
social_core/backends/open_id_connect.py
social_core/storage.py
social_core/tests/models.py
social_core/tests/test_storage.py

This was a breaking change in API that social-app-django and other storages rely on.
your code._

fix: revert API changes from #986

---

pyproject.toml
tox.ini

This makes sure these are compatible regardless what lxml and xmlsec1 upstream does.
Fixes #957
your code._

chore: build lxml and xmlsec1 from source

---

.github/workflows/test.yml
tox.ini

This simplifies the workflow files and performs faster.
your code._

feat(ci): use uv to install dependencies

---

social_core/backends/lastfm.py
social_core/backends/mailru.py

Using md5 is insecure, but these services mandate it, so clearly describe that in the code.
your code._

chore: document md5 usage

---

social_core/backends/vk.py

This is mandated by third-party, but make the md5 usage explicitely documented.
your code._

chore: factor out and document md5 usage in VK

---

social_core/backends/odnoklassniki.py

This is mandated by third-party, but make the md5 usage explicitely documented.
your code._

chore: factor out and document md5 usage in Odnoklassniki

---

.github/renovate.json

This is a more secure way of keeping things up to date.
your code._

feat: pin GitHub action digests

---

.pre-commit-config.yaml

feat: introduce action linter

---

pyproject.toml
social_core/backends/line.py
social_core/backends/uffd.py

The try/except block should be used only for code expected to fail.
your code._

chore: move return statements outside try block

---

pyproject.toml
social_core/strategy.py

The random module is not suitable for use in security scopes.
your code._

fix: use secrets to generate random string

---

pyproject.toml

chore: update licensing info in pyproject.toml

---

README.md

Minor fix to the contributing link in the README.
your code._
None of the boxes apply -- just noticed this when I was starting to dig into another issue and wanted to read CONTRIBUTING.md :)

docs: fix link format to CONTRIBUTING.md in README

---

social_core/backends/microsoft.py

userPrincipalName should be always present, but apparently in some error cases it is null. Make the error message clear in such case.
Fixes #840

fix(microsoft): correctly report missing parameter

---

social_core/backends/azuread.py

Without that the user id is None and caused problems later when storing into the database.
Fixes #749

chore(azure): gracefully handle missing upn

---

pyproject.toml
social_core/backends/base.py
social_core/exceptions.py

This makes it possible to handle these specifically in the caller.
Fixes #916

feat: introduce AuthConnectionError for connection errors

---

.github/workflows/pre-commit-shared.yml
.github/workflows/release.yml
.github/workflows/test.yml
.pre-commit-config.yaml

- we do not need the credentials later
- add zizmor to check these kind of issues

fix(ci): avoid actions/checkout to store credentials

---

social_core/backends/base.py
social_core/backends/mediawiki.py
social_core/backends/oauth.py
social_core/backends/openshift.py

This makes sure that all requests get proper timeout and other parameters.

fix: consistently use wrapped requests

---

social_core/backends/lifescience.py
social_core/tests/backends/test_lifescience.py

Added backend for [Life science AAI](https://lifescience-ri.eu/ls-login.html) with proper tests.
Resolves #1111

feat(backends): Lifescience AAI implementation

---

social_core/tests/backends/base.py
social_core/tests/backends/oauth.py
social_core/tests/backends/open_id.py
social_core/tests/backends/test_cognito.py
social_core/tests/backends/test_nfdi.py

This discovered some issues in testcases not being implemented correctly.

feat: add type annotations to tests

---

.github/workflows/release.yml
.gitignore
MANIFEST.in
pyproject.toml

- add lints
- remove unused manifest parts

feat: add more linting of built packages

---

pyproject.toml
social_core/backends/base.py
social_core/backends/egi_checkin.py
social_core/backends/fence.py
social_core/backends/mendeley.py
social_core/backends/nfdi.py
social_core/backends/oauth.py
social_core/backends/open_id.py
social_core/backends/open_id_connect.py
social_core/tests/backends/test_azuread_b2c.py
social_core/tests/backends/test_open_id_connect.py
social_core/tests/backends/test_saml.py
social_core/tests/test_exceptions.py

- add missing type annotations
- add more type stubs dependencies
- make some type overrides generic by using cast instead of pyright specific overrides

chore: add more type annotations

---

pyproject.toml
social_core/backends/base.py
social_core/tests/actions/actions.py
social_core/tests/actions/test_disconnect.py
social_core/tests/backends/base.py
social_core/tests/backends/legacy.py
social_core/tests/backends/oauth.py
social_core/tests/backends/open_id.py
social_core/tests/backends/test_discourse.py
social_core/tests/backends/test_saml.py
social_core/tests/backends/test_stripe.py
social_core/tests/backends/test_yahoo.py

Only allow selected parameters to requests to allow type checking.

chore: tighten requests interface

---

pyproject.toml
social_core/tests/backends/test_keycloak.py

fix: avoid using mutable as default value

---

pyproject.toml
social_core/tests/backends/test_saml.py

feat(tests): use pathlib to simplify file access

---

pyproject.toml
social_core/backends/lastfm.py
social_core/backends/mailru.py
social_core/backends/odnoklassniki.py
social_core/backends/vk.py

This is mandated by third-party API so rather make specific exceptions istead of allowing that globally.

chore: annotate md5 usage for ruff

---

social_core/backends/azuread_b2c.py
social_core/backends/bitbucket.py
social_core/backends/discourse.py
social_core/backends/gae.py
social_core/backends/oauth.py
social_core/backends/qiita.py
social_core/backends/telegram.py
social_core/exceptions.py
social_core/tests/test_exceptions.py

Add type annotations to exceptions and corrected invocation which passed invalid values as backend.

fix: correct exception initialization

---

social_core/backends/base.py
social_core/backends/evernote.py
social_core/backends/oauth.py

Also make the handling more robust to some parameters.

chore: add type annotations to extra_data processing

---

social_core/tests/actions/actions.py
social_core/tests/actions/test_login.py

chore: add type annotations to actions tests

---

social_core/backends/tripit.py

The `data` attribute is internal implementation, it should be accessed as `nodeValue`. The code was also refactored to be more readable.
This fixes type checking with recent pyright.

fix(tripit): avoid using private minidom interfaces

---

.pre-commit-config.yaml
pyproject.toml

Makes sure the pyproject.toml is nicely ordered.

feat: introduce toml-sorter in pre-commit

---

CHANGELOG.md
pyproject.toml

chore: Version bump 4.6.0

---

social_core/backends/base.py
social_core/utils.py

fix: do not use blank ID_KEY

---

CHANGELOG.md
pyproject.toml

chore: release 4.6.1

---

pyproject.toml
social_core/backends/openstreetmap.py

This is already existing dependency.

fix: use defusedxml to parse osm xml

---

pyproject.toml
social_core/backends/vk.py
social_core/storage.py
social_core/tests/models.py

- remove shadowing where possible
- annotate API usage which can not be easily changed

fix: avoid shadowing builtins

---

pyproject.toml
social_core/tests/backends/open_id.py

This interface is no longer used for logging there, so the patch does nothing useful.

fix: remove monkey patching openid

---

CHANGELOG.md
pyproject.toml

chore: Version bump 4.7.0

---

social_core/tests/actions/test_associate.py
social_core/tests/actions/test_disconnect.py
social_core/tests/backends/test_dummy.py
social_core/tests/backends/test_google.py
social_core/tests/models.py

chore: add type annotations to test models

---

.gitignore
pyproject.toml
tox.ini

- pin exact pytest versions
- add pytest-github-actions-annotate-failures for GitHub action annotations
- configure default pytest options in pyproject.toml instead of tox.ini
- ignore coverage and profiling files from git

chore: update pytest configuration

---

social_core/backends/gitea.py

The query string authentication is deprecated and will be removed.
Fixes #1211

fix(backends): use HTTP headers to authenticate for Gitea

---

pyproject.toml

- update minimal dependency versions to recent and non-vulnerable releases
- depend on PyJWT[crypto] instead of direct dependency on cryptography (Fixes #1268)
- pin exact versions in dev dependencies

fix(deps): update and clarify dependencies

---

.github/workflows/test.yml
pyproject.toml
tox.ini

Upstream support ends in October, so let's drop support for it (no code changes).

chore(deps): drop support for Python 3.9

---

pyproject.toml
social_core/backends/base.py
social_core/tests/actions/actions.py

Let ruff automatically upgrade the code.

chore: use future annotations

---

tox.ini

It is not needed for testing, but for type checking.

fix: include ping extras in tox testing

---

social_core/backends/saml.py

This makes it easier to understand what is misconfigured.

feat: provide user friendly error when permanent id is not found

---

social_core/backends/base.py
social_core/backends/cas.py

feat: introduce logging to the backend classes

---

social_core/backends/saml.py

This makes the SAML authentication easier to configure as it should work
out of the box with most of the SAML providers without explicitly
configuring attributes mapping.

feat(saml): automatically detect common attribute names

---

social_core/backends/apple.py
social_core/backends/azuread_b2c.py
social_core/backends/gae.py
social_core/tests/backends/oauth.py
social_core/tests/backends/test_azuread_b2c.py
social_core/utils.py

- add some missing casts
- add overrides for ty type checker

chore: improve type annotations

---

pyproject.toml
social_core/actions.py
social_core/backends/apple.py
social_core/backends/base.py
social_core/backends/beats.py
social_core/backends/bungie.py
social_core/backends/google.py
social_core/backends/itembase.py
social_core/backends/jawbone.py
social_core/backends/justgiving.py
social_core/backends/line.py
social_core/backends/loginradius.py
social_core/backends/microsoft.py
social_core/backends/oauth.py
social_core/backends/open_id.py
social_core/backends/saml.py
social_core/backends/untappd.py
social_core/backends/weixin.py
social_core/backends/yahoo.py
social_core/pipeline/partial.py
social_core/pipeline/utils.py
social_core/strategy.py

The star-argument should be unpacked before any keyword arguments to make the actual behavior obvious.

fix: corrected star unpacking invocation

---

social_core/backends/base.py

chore: fix type annotation

---

social_core/strategy.py

chore: drop unused strategy methods

---

social_core/backends/azuread_b2c.py
social_core/backends/deezer.py
social_core/backends/linkedin.py
social_core/backends/loginradius.py
social_core/backends/open_id_connect.py
social_core/backends/qiita.py
social_core/backends/qq.py
social_core/backends/stackoverflow.py

- Correctly override method in subclasses
- Reuse existing method where possible

fix: consolidate request_access_token invocations

---

.github/workflows/scorecard.yml

Add Scorecard workflow for supply-chain security

---

CHANGELOG.md
pyproject.toml

chore: releasing 4.8.0

---

social_core/backends/base.py
social_core/pipeline/disconnect.py
social_core/pipeline/mail.py
social_core/pipeline/social_auth.py
social_core/pipeline/user.py
social_core/pipeline/utils.py
social_core/storage.py
social_core/strategy.py
social_core/tests/models.py
social_core/tests/strategy.py

Added type annotations to catch this invocation and pass User instance instead of UserMixin.
Fixes #1344

fix: pass user instance to extra_data() in refresh_token()

---

social_core/backends/azuread.py
social_core/backends/azuread_b2c.py
social_core/backends/base.py
social_core/backends/facebook.py
social_core/backends/google.py
social_core/backends/keycloak.py
social_core/backends/mineid.py
social_core/backends/nationbuilder.py
social_core/backends/oauth.py
social_core/backends/osso.py
social_core/backends/scistarter.py
social_core/backends/seznam.py
social_core/backends/soundcloud.py
social_core/backends/weixin.py
social_core/tests/backends/test_mineid.py

This allows to use the backends with other than hardcoded URLs easily.
Fixes #893

feat: allow to override OAuth2 URLs in settings
